### ISSUE TITLE
Pictures and text, out of the screen

### ISSUE THREAD

**Issue by llrs** [kevinrue/xaringan_carousel#13]
While watching the slides some pictures are cropped like slide 23, 40. Perhaps there is a way to adjust the picture to the size of the slides. Also happens on the text below the pictures, for example slide 18. Not sure if there is an easy solution in this case, perhaps providing alt.text or as captions to the photos?

**Comment by kevinrue** [comment]
I've seen those, but cannot invest the time right now to inspect and fix them myself.

The images are insert with the typical HTML tag <img> which takes attributes width and height, e.g. `<img height='300px'>`.

Feel free to fix if you have the time. Thanks!

**Comment by kevinrue** [comment]
It's all been taken care of. Thanks!
